# Dependabot Configuration
# Automated dependency and security updates

version: 2

updates:
  # Monitor GitHub Actions for security updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    reviewers:
      - "omar120489"
    assignees:
      - "omar120489"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
    # Group updates by action owner
    groups:
      actions-core:
        patterns:
          - "actions/*"
      pnpm:
        patterns:
          - "pnpm/*"
      security:
        patterns:
          - "step-security/*"
          - "aquasecurity/*"
          - "snyk/*"
    # Security updates get priority
    open-pull-requests-limit: 10
    # Auto-merge patch updates (optional - enable after testing)
    # auto-merge: true
    # pull-request-branch-name:
    #   separator: "-"

  # Monitor npm dependencies (frontend)
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    reviewers:
      - "omar120489"
    labels:
      - "dependencies"
      - "frontend"
    groups:
      mui:
        patterns:
          - "@mui/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-router-dom"
      testing:
        patterns:
          - "@testing-library/*"
          - "vitest"
          - "playwright"
    open-pull-requests-limit: 5
    # Ignore major version updates for stable dependencies
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Monitor npm dependencies (backend)
  - package-ecosystem: "npm"
    directory: "/apps/core-api"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    reviewers:
      - "omar120489"
    labels:
      - "dependencies"
      - "backend"
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      fastify:
        patterns:
          - "fastify"
          - "@fastify/*"
    open-pull-requests-limit: 5
    # Ignore major version updates for stable dependencies
    ignore:
      - dependency-name: "@nestjs/*"
        update-types: ["version-update:semver-major"]

  # Monitor Docker dependencies (if using)
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "thursday"
  #   commit-message:
  #     prefix: "docker"
  #   reviewers:
  #     - "omar120489"
  #   labels:
  #     - "dependencies"
  #     - "docker"
