# Dependabot Configuration
# Automated dependency and security updates

version: 2

updates:
  # Monitor GitHub Actions for security updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    reviewers:
      - "omar120489"
    labels:
      - "dependencies"
      - "github-actions"

  # Monitor npm dependencies (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "omar120489"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # Monitor frontend dependencies
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "omar120489"
    labels:
      - "dependencies"
      - "frontend"
    open-pull-requests-limit: 10

  # Monitor core-api dependencies
  - package-ecosystem: "npm"
    directory: "/apps/core-api"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "11:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "omar120489"
    labels:
      - "dependencies"
      - "backend"
    open-pull-requests-limit: 10

  # Monitor reporting dependencies
  - package-ecosystem: "npm"
    directory: "/apps/reporting/traffic-crm-backend-reporting"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "omar120489"
    labels:
      - "dependencies"
      - "backend"
    open-pull-requests-limit: 5

  # Monitor workers dependencies
  - package-ecosystem: "npm"
    directory: "/apps/workers"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "omar120489"
    labels:
      - "dependencies"
      - "workers"
    open-pull-requests-limit: 5

  # Monitor SDK dependencies
  - package-ecosystem: "npm"
    directory: "/packages/sdk-js"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "10:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "omar120489"
    labels:
      - "dependencies"
      - "sdk"
    open-pull-requests-limit: 5
