version: '3.7'

services:
  mcp-server:
    image: "node:22"
    #command: ["host.docker.internal:1521/freepdb1"]
    #build:
    #  context: ..
    #  dockerfile: src/oracle/Dockerfile
    #  platforms:
    #    - "linux/arm64"
    command: tail -f /dev/null
    environment:
      - ORACLE_USER=hr
      - ORACLE_PASSWORD=hr_2025
    volumes:
      - ..:/modelcontextprotocol/servers
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: hr
      POSTGRES_PASSWORD: hr_2025
      POSTGRES_DB: hr