name: CI
on:
  pull_request: { branches: [main, develop, chore/**] }
  push: { branches: [main, develop] }
jobs:
  typecheck-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: ['@apps/core-api','./apps/frontend','@shared-types','@sdk-js/core']
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 10.18.2 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter ${{ matrix.workspace }} typecheck
      - run: pnpm --filter ${{ matrix.workspace }} build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 10.18.2 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 10.18.2 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
