name: E2E - Analytics Dashboard

on:
  pull_request:
    paths:
      - "apps/frontend/**"
      - ".github/workflows/e2e-analytics.yml"
  push:
    branches: [main]
    paths:
      - "apps/frontend/**"
      - ".github/workflows/e2e-analytics.yml"

# Cancel in-progress runs for the same workflow + ref
concurrency:
  group: e2e-analytics-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20'

      - name: Install pnpm
        run: corepack enable

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install workspace dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Playwright browsers
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Install Playwright system dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps chromium

      - name: Run E2E tests (Analytics Dashboard)
        working-directory: apps/frontend
        env:
          NODE_ENV: test
          CI: true
          E2E_BASE_URL: http://localhost:3000
        run: pnpm test:e2e e2e/analytics.spec.ts

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.4.0
        with:
          name: playwright-report-analytics
          path: apps/frontend/playwright-report/
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Playwright traces & videos
        if: failure()
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.4.0
        with:
          name: playwright-traces-analytics
          path: |
            apps/frontend/test-results/**/trace.zip
            apps/frontend/test-results/**/video.webm
          if-no-files-found: ignore
          retention-days: 7

      - name: Comment PR with test results
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Analytics Dashboard E2E tests failed**\n\nPlease check the [test report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
            })

