name: release-please

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please (manifest)
        uses: google-github-actions/release-please-action@v4
        with:
          command: manifest

